### ISSUE TITLE
OG: Wallcop's PERP Post R1/R2 Bug list

### ISSUE THREAD

**Issue by illuminatixs** [illuminatixs/ZarpPerp-issues#4]
What type of problem is it (Bug/Glitch) and what is it ?
Loss of weapon/Ghost Weapon

How did you encounter this bug?
Getting restrained by Jerry in the PD

Time/Date (BST)
18:30 01/06/15

Video/Screenshot of it?
steamcommunity.com/sharedfiles/filedetails/?id=453434014

Extra Information
It said it was on my person in the F2 menu but did not appear on my person in-game

OG poster: Wallcop

**Comment by wallcop100** [comment]
Checked IG and once detained a subject will be stripped of weapons. This is also shown in the code. Closed.
